@hostname=localhost
@port=5135
@api-version=1

GET http://{{hostname}}:{{port}}/patients?api-version={{api-version}} 

###

POST http://{{hostname}}:{{port}}/patients?api-version={{api-version}} 
Content-Type: application/json

{
    "firstname": "Anton",
    "lastname": "Ther",
    "nickname": "Toni",
    "email": "anton.ther@gmail.com"
}
