// <auto-generated />
using BillOMat.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillOMat.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240210075923_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillOMat.Api.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Josef",
                            Lastname = "Fürlinger",
                            Nickname = "Joe"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Daniela",
                            Lastname = "Fürlinger",
                            Nickname = "Dani"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Lea Marie",
                            Lastname = "Fürlinger",
                            Nickname = "Lea"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Finja Sophie",
                            Lastname = "Fürlinger",
                            Nickname = "Finja"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
