# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
    TELERIK_USERNAME: ${{ secrets.MYTELERIKACCOUNTUSERNAME }}
    TELERIK_PASSWORD: ${{ secrets.MYTELERIKACCOUNTPASSWORD }}
    NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    
jobs:
  build:
  
    runs-on: ubuntu-latest  

    defaults:
      run:
        working-directory: './src'    
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        dotnet-quality: 'preview'

    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}\.nuget\packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore workloads
      run: dotnet workload restore
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/TestResults/*.trx
