# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
    TELERIK_USERNAME: ${{ secrets.MYTELERIKACCOUNTUSERNAME }}
    TELERIK_PASSWORD: ${{ secrets.MYTELERIKACCOUNTPASSWORD }}
    
jobs:
  build:
  
    runs-on: ubuntu-latest  

    defaults:
      run:
        working-directory: './src'    
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        dotnet-quality: 'preview'

#    - name: Register Nuget Packages
#      env: # Or as an environment variable
#        TELERIK_USERNAME: ${{ secrets.MYTELERIKACCOUNTPASSWORD }}
#        TELERIK_PASSWORD: ${{ secrets.MYTELERIKACCOUNTUSERNAME }}
#      run: dotnet nuget update source "telerik.com" --username "$telerik_username" --store-password-in-clear-text --password "$telerik_password"
        
    - name: Restore workloads
      run: dotnet workload restore
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
